import {lazy,Suspense,useEffect,useMemo,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,BookOpen,Check,ChevronRight,Eye,Focus,Info,Layers3,Maximize2,Pause,Play,RotateCcw,RotateCw,Search,X} from 'lucide-react';
import {DEFAULT_VISIBLE,type Atlas,type Concept,type SceneState,type SystemId,type View} from './anatomy';
import {VI_SYSTEMS,SYSTEM_VI,LESSONS,describe,conceptSystem,educationalSelections,fold,labelFor,lessonFor,lessonSelection,translatedName,type Lesson} from './education';
import FunctionDiagram from './function-diagram';
import {normalizeAtlas} from './normalize-atlas';
const AnatomyScene=lazy(()=>import('./scene'));
const initial:SceneState={explode:0,visible:DEFAULT_VISIBLE,selected:[],isolate:false,view:'three-quarter',rotate:false,reset:0,lens:'solid'};
const viNumber=(n:number)=>n.toLocaleString('vi-VN');
export default function Home(){
 const [sex,setSex]=useState<'male'|'female'>('male'),[atlas,setAtlas]=useState<Atlas|null>(null),[state,setState]=useState(initial);
 const [progress,setProgress]=useState(0),[error,setError]=useState(''),[query,setQuery]=useState(''),[search,setSearch]=useState(false),[layers,setLayers]=useState(false),[about,setAbout]=useState(false),[chosen,setChosen]=useState<Concept|null>(null);
 const [lesson,setLesson]=useState<Lesson|null>(null),[playing,setPlaying]=useState(false),[phase,setPhase]=useState(0),[speed,setSpeed]=useState(1);
 const [diagramOpen,setDiagramOpen]=useState(false);
 const detailRef=useRef<HTMLElement>(null),phaseRef=useRef(0),searchRef=useRef<HTMLInputElement>(null),triggerRef=useRef<HTMLElement|null>(null);
 const reduced=useRef(matchMedia('(prefers-reduced-motion: reduce)').matches);
 useEffect(()=>{const abort=new AbortController();setAtlas(null);setProgress(0);setError('');setChosen(null);setLesson(null);setPlaying(false);setPhase(0);setState({...initial,visible:sex==='female'?[...DEFAULT_VISIBLE,'integumentary']:DEFAULT_VISIBLE});
 fetch(sex==='male'?'/models/atlas.json':'/models/atlas-female.json',{signal:abort.signal}).then(r=>{if(!r.ok)throw Error('Không tải được danh mục cơ thể. Hãy thử lại.');return r.json();}).then(data=>setAtlas(normalizeAtlas(data))).catch(e=>{if(e.name!=='AbortError')setError('Không tải được dữ liệu cơ thể. Kiểm tra kết nối rồi thử lại.');});return()=>abort.abort();},[sex]);
 useEffect(()=>{phaseRef.current=phase;},[phase]);
 useEffect(()=>{if(!playing||!lesson)return;let frame=0,last=performance.now();const tick=(now:number)=>{const dt=Math.min((now-last)/1000,.1);last=now;phaseRef.current=(phaseRef.current+dt*speed/lesson.duration)%1;setPhase(phaseRef.current);frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[playing,lesson,speed]);
 useEffect(()=>{const visibility=()=>{if(document.hidden)setPlaying(false);};document.addEventListener('visibilitychange',visibility);return()=>document.removeEventListener('visibilitychange',visibility);},[]);
 useEffect(()=>{if(search)searchRef.current?.focus();},[search]);
 useEffect(()=>{if(!search&&!about)return;const previous=document.activeElement as HTMLElement;const dialog=document.querySelector<HTMLElement>('[aria-modal="true"]');const focusable=()=>Array.from(dialog?.querySelectorAll<HTMLElement>('button,a[href],input,select,[tabindex="0"]')??[]).filter(el=>!el.hasAttribute('disabled'));focusable()[0]?.focus();const trap=(e:KeyboardEvent)=>{if(e.key!=='Tab')return;const items=focusable(),first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}};document.addEventListener('keydown',trap);return()=>{document.removeEventListener('keydown',trap);if(previous?.isConnected)previous.focus();};},[search,about]);
 const closeDetail=()=>{setChosen(null);setLesson(null);setPlaying(false);setPhase(0);setState(s=>({...s,selected:[],isolate:false,lesson:undefined,phase:0}));triggerRef.current?.focus();};
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{if(e.key==='Escape'){setSearch(false);setLayers(false);setAbout(false);closeDetail();}if(e.key==='/'&&!(e.target instanceof HTMLInputElement)){e.preventDefault();setSearch(true);}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[]);
 const parts=useMemo(()=>new Map(atlas?.parts.map(p=>[p.id,p])),[atlas]);
 const educational=useMemo(()=>atlas?educationalSelections(atlas):new Map<string,Concept>(),[atlas]);
 const counts=useMemo(()=>Object.fromEntries(VI_SYSTEMS.map(s=>[s.id,atlas?.parts.filter(p=>p.system===s.id).length??0])),[atlas]);
 const systems=VI_SYSTEMS.filter(s=>counts[s.id]>0);
 const selected=chosen?.elements.map(id=>parts.get(id)).find(Boolean);
 const selectedSystem=chosen?conceptSystem(chosen,parts):(selected?.system??'connective');
 const results=useMemo(()=>{if(!atlas)return[];const q=fold(query.trim());return atlas.concepts.filter(c=>q?fold(labelFor(c,conceptSystem(c,parts))).includes(q)||fold(c.name).includes(q)||fold(c.id).includes(q):!!translatedName(c.name)).sort((a,b)=>Number(!translatedName(a.name))-Number(!translatedName(b.name))||a.name.length-b.name.length).slice(0,60);},[atlas,query,parts]);
 const choose=(c:Concept)=>{triggerRef.current=document.activeElement as HTMLElement;setChosen(c);setLesson(null);setPlaying(false);setPhase(0);setSearch(false);setLayers(false);setState(s=>({...s,selected:c.elements,isolate:false,rotate:false,lesson:undefined}));setTimeout(()=>detailRef.current?.focus(),0);};
 const choosePart=(id:string)=>{const p=parts.get(id);if(p){const exact=atlas?.concepts.find(c=>c.id===p.conceptId&&c.elements.includes(id));choose(educational.get(id)??exact??{id:p.conceptId,name:p.name,elements:[id]});}};
 const startLesson=(item:Lesson)=>{if(!atlas)return;triggerRef.current=document.activeElement as HTMLElement;const ids=lessonSelection(atlas,item);setLesson(item);setChosen(null);setDiagramOpen(false);setPhase(0);phaseRef.current=0;setPlaying(!reduced.current);setSearch(false);setLayers(false);setState(s=>({...s,visible:item.systems,selected:ids,isolate:true,explode:0,rotate:false,lens:'solid',lesson:item.id,reset:s.reset+1}));setTimeout(()=>detailRef.current?.focus(),0);};
 const reset=()=>{closeDetail();setSearch(false);setLayers(false);setState(s=>({...initial,visible:sex==='female'?[...DEFAULT_VISIBLE,'integumentary']:DEFAULT_VISIBLE,reset:s.reset+1}));};
 const preset=(visible:SystemId[])=>{closeDetail();setState(s=>({...s,visible,selected:[],isolate:false}));};
 const activeStep=lesson?Math.max(0,Math.min(lesson.steps.length-1,Math.floor((Number.isFinite(phase)?phase:0)*lesson.steps.length))):0;
 const related=chosen?lessonFor(chosen.name,selectedSystem):null;
 const detailOpen=!!chosen||!!lesson;
 return <main className={'studio '+(detailOpen?'has-detail':'')+(state.explode>.1?' is-exploded':'')}>
  <Suspense fallback={<div className="scene"/>}>{atlas&&<AnatomyScene atlas={atlas} state={{...state,inspectorOpen:detailOpen,lesson:lesson?.id,phase}} onSelect={choosePart} onProgress={setProgress} onError={setError}/>}</Suspense>
  <div className="stage-shade"/>
  <header className="topbar">
   <button className="brand" onClick={reset} aria-label="Về toàn bộ cơ thể"><span className="brand-mark">h<span>·</span></span><span>Cơ thể người<small>Một thế giới bên trong bạn</small></span></button>
   <div className="atlas-switch" aria-label="Chọn cơ thể tham chiếu">{(['male','female'] as const).map(s=><button key={s} aria-pressed={sex===s} className={sex===s?'selected':''} onClick={()=>setSex(s)}>{s==='male'?'Nam':'Nữ'}</button>)}</div>
   <div className="header-actions"><button aria-label="Tìm bộ phận" className="search-trigger" onClick={()=>{setSearch(true);setLayers(false);}}><Search size={17}/><span>Tìm bộ phận</span><kbd>/</kbd></button><button className="icon-button" aria-label="Nguồn dữ liệu và giới thiệu" onClick={()=>setAbout(true)}><Info size={19}/></button></div>
  </header>
  {!detailOpen&&<section className="intro-copy"><span className="section-kicker">Chạm để khám phá</span><h1>Hiểu cơ thể.<br/>Hiểu chính mình.</h1><p>Mỗi cơ quan là một câu chuyện.<br/>Chọn một bộ phận và bắt đầu tìm hiểu.</p></section>}
  <aside className={'systems-panel '+(layers?'mobile-open':'')} aria-label="Các hệ cơ quan">
   <div className="panel-heading"><h2>Các hệ cơ quan</h2><button className="icon-button mobile-only" onClick={()=>setLayers(false)} aria-label="Đóng các hệ cơ quan"><X size={18}/></button><span className="desktop-only">{systems.length}</span></div>
   <div className="presets"><button onClick={()=>preset(DEFAULT_VISIBLE)}>Toàn thân</button><button onClick={()=>preset(['skeletal'])}>Bộ xương</button><button onClick={()=>preset(['cardiac','respiratory','digestive','urinary','endocrine'])}>Nội tạng</button></div>
   <div className="system-list">{systems.map(s=><div key={s.id} className={'system-row '+(state.visible.includes(s.id)?'enabled':'')}><button className="system-label" onClick={()=>preset([s.id])} title={'Chỉ xem '+s.name.toLowerCase()}><i style={{background:s.color}}/>{s.name}</button><button className="visibility" role="switch" aria-checked={state.visible.includes(s.id)} aria-label={'Hiện '+s.name.toLowerCase()} onClick={()=>{closeDetail();setState(v=>({...v,visible:v.visible.includes(s.id)?v.visible.filter(x=>x!==s.id):[...v.visible,s.id]}));}}>{state.visible.includes(s.id)?<Eye size={15}/>:<span className="hidden-eye"/>}</button></div>)}</div>
   <div className="coverage-note">{sex==='female'?'Mẫu nữ: cơ quan chọn lọc; xương và cơ chưa đầy đủ.':'Mẫu nam: cấu trúc tham chiếu; độ phủ tùy cơ quan.'}<button onClick={()=>setAbout(true)}>Xem nguồn <ArrowRight size={12}/></button></div>
  </aside>
  {!detailOpen&&<aside className="discover-panel" aria-label="Khám phá hoạt động"><div className="panel-heading"><h2>Cơ thể hoạt động thế nào?</h2><BookOpen size={17}/></div>{LESSONS.map((l,i)=><button className="lesson-entry" key={l.id} onClick={()=>startLesson(l)} disabled={progress<100}><span className={'lesson-symbol symbol-'+l.id}>{['♡','◡','∿','⋈'][i]}</span><span><strong>{l.name}</strong><small>{l.summary}</small></span><ChevronRight size={16}/></button>)}<p>Chọn một hành trình để xem cơ quan hoạt động từng bước.</p></aside>}
  <nav className="view-controls" aria-label="Góc nhìn">{(['three-quarter','front','side','back'] as View[]).map((v,i)=><button key={v} aria-label={['Góc nghiêng','Mặt trước','Mặt bên','Mặt sau'][i]} title={['Góc nghiêng','Mặt trước','Mặt bên','Mặt sau'][i]} className={state.view===v?'active':''} onClick={()=>setState(s=>({...s,view:v,reset:s.reset+1,rotate:false}))}>{['¾','T','B','S'][i]}</button>)}<span/><button aria-label={state.rotate?'Dừng xoay':'Tự xoay'} onClick={()=>setState(s=>({...s,rotate:!s.rotate}))}>{state.rotate?<Pause size={16}/>:<RotateCw size={17}/>}</button><button aria-label="Đặt lại góc nhìn" onClick={reset}><RotateCcw size={17}/></button></nav>
  <div className="stage-caption"><span className="live-dot"/>{lesson?'Minh họa chuyển động · không theo thời gian thực':chosen?labelFor(chosen,selectedSystem):'Cơ thể '+(sex==='male'?'nam':'nữ')+' · '+viNumber(atlas?.parts.length??0)+' cấu trúc'}</div>
  <section className="bottom-dock" aria-label="Điều khiển mô hình"><button className="mobile-only" onClick={()=>setLayers(v=>!v)} aria-label="Mở các hệ cơ quan"><Layers3 size={20}/></button><div className="lens-switch"><button className={state.lens!=='xray'?'active':''} aria-pressed={state.lens!=='xray'} onClick={()=>setState(s=>({...s,lens:'solid'}))}>Giải phẫu</button><button className={state.lens==='xray'?'active':''} aria-pressed={state.lens==='xray'} onClick={()=>setState(s=>({...s,lens:'xray'}))}>Xuyên thấu</button></div><div className="explode-control"><label htmlFor="explode">Tách các bộ phận <output>{Math.round(state.explode*100)}%</output></label><input id="explode" aria-label="Tách các bộ phận" type="range" min="0" max="100" value={state.explode*100} onChange={e=>{setLesson(null);setPlaying(false);setState(s=>({...s,explode:+e.target.value/100,isolate:false,rotate:false,lesson:undefined}));}}/></div><button className="dock-reset" onClick={reset} aria-label="Trở về toàn thân"><RotateCcw size={17}/></button></section>
  <footer className="studio-footer"><span>Kéo để xoay <i/> Cuộn để phóng to <i/> Chạm để tìm hiểu</span><button onClick={()=>setAbout(true)}>Dữ liệu mở · Nguồn khoa học <ArrowRight size={12}/></button></footer>
  {progress<100&&!error&&<div className="loading" role="status"><div className="loading-copy"><span>Đang mở thế giới bên trong bạn</span><strong>{progress}%</strong></div><div className="loading-track"><i style={{width:progress+'%'}}/></div><small>Mô hình chi tiết đang được tải theo từng phần.</small></div>}
  {error&&<div className="loading error" role="alert"><p>{error}</p><button onClick={()=>location.reload()}>Tải lại mô hình</button></div>}
  {detailOpen&&<aside ref={detailRef} tabIndex={-1} className="detail-sheet" role="dialog" aria-modal="false" aria-labelledby="detail-title">
   <div className="detail-top"><span className="section-kicker">{lesson?'Khám phá hoạt động':SYSTEM_VI[selectedSystem].name}</span><button className="icon-button" aria-label="Đóng giải thích" onClick={closeDetail}><X size={20}/></button></div>
   <div className="detail-scroll">
    <h2 id="detail-title">{lesson?lesson.name:chosen&&labelFor(chosen,selectedSystem)}</h2>
    {lesson?<><p className="lesson-question">{lesson.question}</p>{sex==='male'&&lesson.id==='lungs'&&<p className="context-note">Mô hình thể hiện cây phế quản và mạch máu; chưa có bề mặt nhu mô phổi.</p>}<button className="mobile-only diagram-toggle" onClick={()=>setDiagramOpen(v=>!v)} aria-expanded={diagramOpen}>{diagramOpen?'Ẩn sơ đồ chức năng':'Xem sơ đồ chức năng'}<ChevronRight size={14}/></button><div className={'diagram-wrap '+(diagramOpen?'open':'')}><FunctionDiagram lesson={lesson.id} phase={phase}/></div><div className="playback"><button className="play-button" onClick={()=>setPlaying(v=>!v)} aria-label={playing?'Tạm dừng minh họa':'Phát minh họa'}>{playing?<Pause size={17}/>:<Play size={17}/>}</button><input aria-label="Tiến độ hoạt động" type="range" min="0" max="999" value={Math.round(phase*999)} onChange={e=>{setPlaying(false);setPhase(+e.target.value/999);}}/><select aria-label="Tốc độ minh họa" value={speed} onChange={e=>setSpeed(+e.target.value)}><option value=".5">0,5×</option><option value="1">1×</option><option value="1.5">1,5×</option></select></div><div className="step-tabs" aria-label="Các giai đoạn">{lesson.steps.map((s,i)=><button key={s.title} className={i===activeStep?'active':''} aria-label={s.title} aria-current={i===activeStep?'step':undefined} onClick={()=>{setPlaying(false);setPhase(i/lesson.steps.length+.002);}}>{i+1}</button>)}</div><div className="step-copy"><h3>{lesson.steps[activeStep].title}</h3><p>{lesson.steps[activeStep].body}</p></div><div className="did-you-know"><span>Bạn có biết?</span><p>{lesson.fact}</p></div><a className="source-link" href={lesson.source} target="_blank" rel="noreferrer">Đọc nguồn: {lesson.sourceName} <ArrowRight size={13}/></a><p className="context-note">Sơ đồ chức năng được giản lược để dễ hiểu. Màu sắc và tốc độ là quy ước minh họa.</p></>:<><p className="structure-description">{chosen&&describe(chosen,selectedSystem)}</p>{sex==='male'&&chosen&&/^(left |right )?lung/.test(chosen.name.toLowerCase())&&<p className="context-note">Phần 3D đang hiển thị cây phế quản và mạch máu của phổi. Gói dữ liệu chưa có bề mặt nhu mô phổi.</p>}{related&&<button className="activity-link" onClick={()=>startLesson(related)}><span className="play-orbit"><Play size={18}/></span><span><strong>Xem hoạt động</strong><small>{related.name}</small></span><ArrowRight size={18}/></button>}<div className="detail-facts"><span>Vị trí trong hệ<strong>{SYSTEM_VI[selectedSystem].name}</strong></span><span>Cấu trúc được chọn<strong>{chosen?.elements.length} bộ phận</strong></span></div><details className="source-details"><summary>Đối chiếu dữ liệu gốc</summary><p>Tên nguồn: {chosen?.name}</p><p>Mã: {chosen?.id}</p><p>{atlas?.source??'BodyParts3D'} · {atlas?.version}</p>{chosen&&!translatedName(chosen.name)&&<p>Tên chuyên sâu này chưa có bản dịch được biên tập. Nhãn phía trên dùng hệ cơ quan và mã định danh để đối chiếu chính xác.</p>}</details></>}
   </div>
   <div className="detail-actions">{chosen&&<button className="primary-action" onClick={()=>setState(s=>({...s,isolate:!s.isolate,explode:0}))}><Focus size={18}/>{state.isolate?'Xem cùng cơ thể':'Xem cận cảnh'}<Maximize2 size={16}/></button>}<button className="back-action" onClick={reset}><ArrowLeft size={16}/>Trở lại toàn thân</button></div>
  </aside>}
  {search&&<div className="overlay" onClick={()=>setSearch(false)}><section className="search-dialog" role="dialog" aria-modal="true" aria-label="Tìm bộ phận" onClick={e=>e.stopPropagation()}><div className="search-input"><Search size={20}/><input ref={searchRef} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tìm tim, phổi, xương đùi…" aria-label="Tên bộ phận"/><button className="icon-button" aria-label="Đóng tìm kiếm" onClick={()=>setSearch(false)}><X size={20}/></button></div><p className="search-hint">{query?'Kết quả phù hợp':'Bắt đầu với một cơ quan quen thuộc'}</p><div className="search-results">{results.length?results.map(c=><button key={c.id} onClick={()=>choose(c)}><span>{labelFor(c,conceptSystem(c,parts))}<small>{SYSTEM_VI[conceptSystem(c,parts)??'connective'].name}</small></span><ArrowRight size={16}/></button>):<p>Chưa tìm thấy. Thử tên khác hoặc mã của cấu trúc.</p>}</div></section></div>}
  {about&&<div className="overlay" onClick={()=>setAbout(false)}><section className="about-dialog" role="dialog" aria-modal="true" aria-labelledby="about-title" onClick={e=>e.stopPropagation()}><button className="icon-button close-about" aria-label="Đóng giới thiệu" onClick={()=>setAbout(false)}><X size={20}/></button><span className="section-kicker">Học từ những nguồn có thể đối chiếu</span><h2 id="about-title">Một cơ thể.<br/>Nhiều điều để hiểu.</h2><p>Mô hình nam sử dụng BodyParts3D 4.0. Mô hình nữ sử dụng Human Reference Atlas v1.5 của HuBMAP, có bề mặt và các cơ quan chọn lọc; độ phủ xương và cơ còn hạn chế.</p><p>Hai bộ dữ liệu có phạm vi khác nhau và không đại diện cho mọi biến thể cơ thể người. Đây là trải nghiệm giáo dục, không dùng cho chẩn đoán.</p><div className="source-items"><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/download.html" target="_blank" rel="noreferrer"><Check size={15}/>BodyParts3D · DBCLS <ArrowRight size={14}/></a><a href="https://doi.org/10.48539/HBM352.BTSQ.586" target="_blank" rel="noreferrer"><Check size={15}/>Human Reference Atlas · HuBMAP <ArrowRight size={14}/></a><a href="/ATTRIBUTION.md" target="_blank"><Check size={15}/>Ghi công và giấy phép CC BY 4.0 <ArrowRight size={14}/></a></div><p className="context-note">Nội dung hoạt động tham khảo NHLBI và NIDDK. Mô hình bề mặt không chứa đầy đủ cấu trúc vi thể; sơ đồ hoạt động được trình bày riêng để tránh nhầm với hình học nguồn.</p></section></div>}
 </main>;
}
